Repository Eisbison/TheOtherRoles, pull requests merged in 2021-12, with the labels that each got.

#222 Show an orange flash to the killer of the bait, can be turned off in settings.
  TheOtherRoles/CustomOptionHolder.cs
  TheOtherRoles/Patches/PlayerControlPatch.cs
Labels: ✨ enhancement, 🥳 New Role

#250 Updated README.md file
  README.md
Labels: ✨ enhancement

#266 Fix Evil Guesser cannot guess
  TheOtherRoles/TheOtherRoles.cs
Labels: 🥴 bug, ✨ enhancement
